title: Natural
description: Natural is a Javascript library for natural language processing
remote_theme: pmarsceill/just-the-docs

# Theme settings:
site_author: Various authors
repo_url: "https://github.com/NaturalNode/natural"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
